heat_template_version: 2014-10-16

description: |
  A template that deploys Ansible Tower onto a single Linux server.

parameter_groups:

- label: Server Settings
  parameters:
  - flavor
  - image

- label: rax-dev-params
  # These are parameters that will not be displayed in the portal. The purpose
  # of these parameters is for users who are developing or testing newer or
  # different setups. If any of these parameters are changed, there is a good
  # chance this stack will fail to properly deploy.
  parameters:
  - ansible_tower_tarball
  - server_name

parameters:

  flavor:
    label: Server Size
    description: |
      The size is based on the amount of RAM for the provisioned server.
    type: string
    default: 1 GB General Purpose v1
    constraints:
      - allowed_values:
        - 1 GB General Purpose v1
        - 2 GB General Purpose v1
        - 4 GB General Purpose v1
        - 8 GB General Purpose v1
        - 15 GB I/O v1
        - 30 GB I/O v1
        - 1GB Standard Instance
        - 2GB Standard Instance
        - 4GB Standard Instance
        - 8GB Standard Instance
        - 15GB Standard Instance
        - 30GB Standard Instance
        description: must be a valid Nova Cloud Server flavor.

  image:
    label: Operating System
    description: |
      Server image used for all servers that are created as a part of this
      deployment
    type: string
    default: Ubuntu 14.04 LTS (Trusty Tahr) (PV)
    constraints:
    - allowed_values:
      - Ubuntu 12.04 LTS (Precise Pangolin) (PVHVM)
      - Ubuntu 14.04 LTS (Trusty Tahr) (PV)
      description: Must be a supported operating system.

  server_name:
    label: Server Hostname
    description: The instance name
    type: string
    default: ansible-tower

  ansible_tower_tarball:
    label: Ansible Tarball
    description: Location of the Ansible Tower installer
    type: string
    default: |
      http://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-latest.tar.gz

resources:

  wait_condition:
    type: OS::Heat::SwiftSignal
    properties:
      handle: { get_resource: wait_condition_handle }
      timeout: 1800

  wait_condition_handle:
    type: OS::Heat::SwiftSignalHandle

  ssh_key:
    type: "OS::Nova::KeyPair"
    properties:
      name: { get_param: "OS::stack_id" }
      save_private_key: true

  # Random password generation
  ansible_admin_pass:
    type: "OS::Heat::RandomString"
    properties:
      length: 16
      sequence: lettersdigits

  postgres_admin_pass:
    type: "OS::Heat::RandomString"
    properties:
      length: 16
      sequence: lettersdigits

  redis_admin_pass:
    type: "OS::Heat::RandomString"
    properties:
      length: 16
      sequence: lettersdigits

  munin_admin_pass:
    type: "OS::Heat::RandomString"
    properties:
      length: 16
      sequence: lettersdigits

  ansible_tower:
    type: "OS::Nova::Server"
    properties:
      key_name: { get_resource: ssh_key }
      flavor: { get_param: flavor }
      image: { get_param: image }
      name: { get_param: server_name }
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
      config_drive: "true"
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #cloud-config
            package_update: true
            packages:
              - python-dev
              - python-yaml
              - python-paramiko
              - python-jinja2
              - python-pip
            write_files:
            # Write out options file
              - path: /root/tower_setup_conf.yml
                permissions: '0644'
                content: |
                  admin_password: %ansible_admin_pass%
                  database: internal
                  munin_password: %munin_admin_pass%
                  pg_password: %postgres_admin_pass%
                  primary_machine: localhost
                  redis_password: %redis_admin_pass%
            # Write out the inventory file
              - path: /root/inventory
                permissions: '0644'
                content: |
                  [primary]
                  localhost

                  [all:children]
                  primary
            # Install Script
              - path: /root/tower_install.sh
                permissions: '0544'
                content: |
                  #!/bin/bash -v
                  set -e
                  pip install ansible
                  # Pull and extract the installer
                  wget -ct0 %ansible_tower_tarball%
                  tar xzf ansible-tower-setup-latest.tar.gz
                  # Get the extracted folder name
                  ANSIBLE_SETUP_FOLDER=`tar tf ansible-tower-setup-latest.tar.gz | awk -F/ '{ print $1 }' | uniq`
                  # Copy everything to working directory and install
                  cp /root/inventory /root/$ANSIBLE_SETUP_FOLDER/inventory
                  cp /root/tower_setup_conf.yml /root/$ANSIBLE_SETUP_FOLDER/tower_setup_conf.yml
                  cd $ANSIBLE_SETUP_FOLDER
                  ./setup.sh
                  ufw allow 443
                  wc_notify --data-binary '{"status": "SUCCESS"}'
            runcmd:
              - /root/tower_install.sh
          params:
            "%ansible_tower_tarball%": { get_param: ansible_tower_tarball }
            "%ansible_admin_pass%": { get_attr: [ansible_admin_pass, value] }
            "%postgres_admin_pass%": { get_attr: [postgres_admin_pass, value] }
            "%redis_admin_pass%": { get_attr: [redis_admin_pass, value] }
            "%munin_admin_pass%": { get_attr: [munin_admin_pass, value] }
            "%server_name%": { get_param: server_name }
            wc_notify: { get_attr: ['wait_condition_handle', 'curl_cli'] }

outputs:
  private_key:
    description: SSH Private Key
    value: { get_attr: [ssh_key, private_key] }

  ansible_url:
    value:
      str_replace:
        template: "https://%server_ip%"
        params:
          "%server_ip%": { get_attr: [ ansible_tower, accessIPv4 ] }
    description: Tower URL

  server_ip:
    value: { get_attr: [ ansible_tower, accessIPv4 ] }
    description: Server IP

  ansible_username:
    value: admin
    description: Admin Username

  ansible_password:
    value: { get_attr: [ansible_admin_pass, value] }
    description: Admin Password

  server_data:
    value: { get_attr: [ wait_condition, data ] }
    description: Data from wait condition to report script status
